- name: Create a VM from a template
  hosts: localhost
  vars_prompt:
    - name: "vcenter_hostname"
      prompt: "Enter vcenter hostname or IP"
      private: no
    - name: "vcenter_user"
      prompt: "Enter vcenter username"
      private: no
      default: "administrator@vsphere.local"
    - name: "vcenter_pass"
      prompt: "Enter vcenter password"
    - name: "vm_name"
      prompt: "Enter name for your vm"
      private: no
      default: "vmtest1"
    - name: "Datastore"
      prompt: "Enter name of your datastore"
      private: no
      default: "FreeNAS_LabVMware"
    - name: "Datacenter"
      prompt: "Enter your datacenter"
      private: no
      default: "Datacenter"
    - name: "size_disk"
      prompt: "Enter size for the disk on your vm"
      private: no
      default: "2"
    - name: "memory"
      prompt: "Enter number of memory for your vm"
      private: no
      default: "512"
    - name: "cpu"
      prompt: "Enter number of cpu for your vm"
      private: no
      default: "1"
    - name: "ip"
      prompt: "Enter the IP you want for your vm"
      private: no
      default: "10.10.10.200"

  tasks:
  - name: Create a VM from template
    vmware_guest:
      validate_certs: false
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      folder: VMtemplate
      name: "{{ vm_name }}"
      state: poweredoff
      guest_id: centos64Guest
      datastore: "{{ Datastore }}"
      datacenter: "{{ Datacenter }}"
      cluster: Cluster
      disk:
      - size_gb: "{{ size_disk }}"
        type: eagerzeroedthick
      hardware:
        memory_mb: "{{ memory }}"
        num_cpus: "{{ cpu }}"
        num_cpu_cores_per_socket: 1
        scsi: paravirtual
      networks:
      - name: VM Network
        mac: aa:bb:dd:aa:00:14
        ip: "{{ ip }}"
        netmask: 255.255.255.0
        device type: vmxnet3
    delegate_to: localhost
    register: deploy
